name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Update lock file if needed
        run: |
          poetry lock --no-update

      - name: Install dependencies
        run: |
          make install

      - name: Run linter and pytest
        run: |
          make check

      - name: Generate coverage report
        run: |
          poetry run pytest --cov=hexlet_code --cov-report=xml

      - name: Check for coverage.xml
        run: |
          ls -la coverage.xml

      - name: Install Code Climate Reporter
        run: |
          gem install cc-test-reporter

      - name: Print CC_TEST_REPORTER_ID
        run: |
          echo "CC_TEST_REPORTER_ID is set"
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Upload coverage to Code Climate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          cc-test-reporter format-coverage coverage.xml
          cc-test-reporter after-build --coverage-input-type coverage.py --exit-code ${{ job.status }}